- name: onyx_upgrade
  hosts: ONYX
  gather_facts: no
  connection: network_cli
  become: yes
  become_method: enable
  vars:
    ansible_network_os: onyx
    local_path: "/swgwork/eddies/ansible/ansible-playbooks/"
    transfer_protocol: scp
    text_config_folder: /var/opt/tms/text_configs/
  remote_user: admin
  tasks:

    - name: get_timestamp
      shell: date +%Y.%m.%d_%H_%M_%S
      register: time

    - name: create_dir
      local_action: file
      args:
        path: "{{local_path}}"
        state: directory
        mode: 01777

      run_once: true

    - name: create_text_config
      onyx_config:
        commands: configuration text generate active running save {{inventory_hostname}}.{{time.stdout}}
        backup: no

    - name: copy_text_file_from_switch
      net_get:
         dest: "{{local_path}}"
         src: "{{text_config_folder}}/{{inventory_hostname}}.{{time.stdout}}"
         protocol: "{{transfer_protocol}}"
    - debug:
       msg: "File {{inventory_hostname}}.{{time.stdout}} was copied to {{inventory_dir}}/{{local_path}}"
