- name: onyx_golden_mlag_L2_playbook
  hosts: golden_onyx
  gather_facts: no
  strategy: free
  connection: network_cli
  become: yes
  become_method: enable
  vars:
    ansible_network_os: onyx
  tasks:
  - onyx_config:
      lines:
        - interface ethernet 1/1 description "another test"
